# Define which backend to use
selected_backend: samplev1  # Change to "openai" to switch models

backends:
  samplev1:
    model: "sample"
    temperature: 0.5
    initial_prompt: "You are a wise Dungeon Master narrating an epic tale full of mystery and adventure."

  chatgptv1:
    model: "gpt-4"
    temperature: 0.7
    initial_prompt: "You are a wise Dungeon Master narrating an epic tale full of mystery and adventure."
